---
name: Static analysis

on:
  pull_request:
  push:
    paths:
      - '**.php'
      - '*psalm.xml'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock' )}}

      - name: Run Psalm
        run: make static-code-analysis
